apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example-api
          image: local/example:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              cpu: "25m"
              memory: "10Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  type: NodePort
  selector:
    app: example
  ports:
    - port: 8080
      targetPort: 8080
