apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 2  # Adjust replicas if needed for scalability
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example-api
          image: local/example:latest  # Minikube local image
          imagePullPolicy: Never  # This ensures Minikube uses the local image
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              cpu: "25m"
              memory: "10Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  type: NodePort
  selector:
    app: example
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001  # You can specify a custom NodePort if needed
