# deploy/k8s.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-devex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-devex
  template:
    metadata:
      labels:
        app: local-devex
    spec:
      containers:
        - name: local-devex
          image: local/devex:v1
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: local-devex-svc
spec:
  selector:
    app: local-devex
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
