name: CI/CD with Kubernetes and Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Minikube
        uses: medyagh/setup-minikube@v0.0.14
        with:
          driver: docker
          kubernetes-version: 'v1.26.0'

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube addons enable ingress

      - name: Configure Docker environment
        run: |
          minikube docker-env | tee docker-env.sh
          source docker-env.sh
          echo "DOCKER_TLS_VERIFY=$(grep DOCKER_TLS_VERIFY docker-env.sh | cut -d'=' -f2)" >> $GITHUB_ENV
          echo "DOCKER_HOST=$(grep DOCKER_HOST docker-env.sh | cut -d'=' -f2)" >> $GITHUB_ENV
          echo "DOCKER_CERT_PATH=$(grep DOCKER_CERT_PATH docker-env.sh | cut -d'=' -f2)" >> $GITHUB_ENV
          cat docker-env.sh

      - name: Build Docker image
        run: |
          docker build -t example:latest .
          docker images

      - name: Verify image in Minikube
        run: minikube image ls

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deploy/k8s.yaml
          kubectl rollout status deployment/example --timeout=180s
          kubectl get pods,svc
