name: CI for File Push

on:
  push:
    branches:
      - main  # You can replace `main` with any branch you want to track
    paths:
      - 'app.py'  # Trigger the workflow only if app.py is changed

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Replace with your desired Python version

      # Step 3: Install dependencies (including pytest)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt with pytest listed

      # Step 4: Run tests with pytest
      - name: Run tests
        run: |
          pytest  # Run tests using pytest

      # Step 5: Additional steps (Build, Deploy, or custom actions)
      - name: Build or deploy
        run: |
          echo "Running build or deployment steps here"

      # Optional: If you're using Minikube or Kubernetes
      - name: Set up Minikube (optional)
        uses: medyagh/setup-minikube@latest

      - name: Start Minikube (optional)
        run: |
          minikube start --driver=docker
          kubectl cluster-info

      - name: Apply Kubernetes deployment (optional)
        run: |
          kubectl apply -f deploy/k8s.yaml  # Replace with your deployment YAML file
          kubectl wait --for=condition=ready pod -l app=example --timeout=60s

      # Step 6: Clean up after completion (optional)
      - name: Clean up Minikube (optional)
        run: |
          minikube delete
