name: CI for File Push

on:
  push:
    branches:
      - main  # Trigger workflow on push to the `main` branch
    paths:
      - '*'  # Trigger on any file change

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure pytest is in requirements.txt

      # Step 4: List files for debugging
      - name: List files for debugging
        run: |
          ls -R  # List all files recursively

      # Step 5: Run tests using pytest
      - name: Run tests using pytest
        run: |
          pytest tests/  # Specify the test directory

      # Step 6: Additional steps (Build, Deploy, or custom actions)
      - name: Build or deploy
        run: |
          echo "Running build or deployment steps here"
