name: CI/CD with Kubernetes and Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@v0.0.14
        with:
          driver: docker
          kubernetes-version: 'v1.26.0'

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube addons enable ingress

      - name: Build Docker image
        run: minikube image build -t example:latest .

      - name: Verify image
        run: minikube image ls

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deploy/k8s.yaml
          kubectl rollout status deployment/example --timeout=180s
          kubectl get pods,svc
