name: CI for Minikube Deployment

on:
  push:
    branches:
      - main
    paths:
      - '**'  # All files

jobs:
  minikube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Start Minikube with Docker driver
        run: |
          minikube start --driver=docker
          eval $(minikube docker-env)

      - name: Build Docker image inside Minikube
        run: |
          docker build -t local/example:latest .

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deploy/k8s.yaml
          kubectl wait --for=condition=ready pod -l app=example --timeout=1200s

      - name: Get Service URL
        id: get_service_url
        run: |
          SERVICE_URL=$(minikube service example --url)
          echo "Service URL: $SERVICE_URL"
          echo "url=$SERVICE_URL" >> $GITHUB_OUTPUT

      - name: Test the service with curl
        run: |
          curl ${{ steps.get_service_url.outputs.url }}

      - name: Clean up Minikube
        run: |
          minikube delete
