name: CI/CD with Kubernetes and Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Minikube
        uses: medyagh/setup-minikube@v0.0.14

      - name: Enable Minikube Ingress (Optional)
        run: minikube addons enable ingress

      - name: Set Minikube Docker environment
        run: eval $(minikube -p minikube docker-env)

      - name: Build Docker image inside Minikube
        run: |
          docker build -t example:latest .
          # Optional: Check if the image is available in Minikube
          docker images

      - name: Load image into Minikube
        run: minikube image load example:latest

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deploy/k8s.yaml
          echo "Waiting for deployment rollout..."
          kubectl rollout status deployment/example --timeout=180s || {
            echo "Deployment failed to become ready"; 
            kubectl get pods -l app=example;
            kubectl describe pod -l app=example;
            kubectl logs -l app=example;
            exit 1;
          }
