name: CI

on:
  pull_request:
    branches:
      - main  # Adjust to your branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Minikube

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          kubectl cluster-info

      - name: Apply Kubernetes Deployment and Service
        run: |
          kubectl apply -f your-deployment-file.yaml
          kubectl wait --for=condition=ready pod -l app=example --timeout=60s

      - name: Expose Service using port-forward
        run: |
          kubectl port-forward svc/example 8080:8080 &
          sleep 5  # Give it a little time to set up

      - name: Get Service URL (using port-forward)
        id: get_service_url
        run: |
          echo "Service should be available on localhost:8080"
        
      - name: Test the service using curl
        run: |
          curl http://localhost:8080  # This will hit the port-forwarded service

      - name: Clean up Minikube
        run: |
          minikube delete
