name: CI

on:
  - pull_request

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Minikube

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          kubectl cluster-info

      - name: Apply Kubernetes Deployment and Service
        run: |
          kubectl apply -f your-deployment-file.yaml
          kubectl wait --for=condition=ready pod -l app=example --timeout=60s

      - name: Get Service URL
        id: get_service_url
        run: |
          SERVICE_URL=$(minikube service example --url)
          echo "Service URL: $SERVICE_URL"
          echo "::set-output name=url::$SERVICE_URL"

      - name: Test the service using curl
        run: |
          curl ${{ steps.get_service_url.outputs.url }}

      - name: Clean up Minikube
        run: |
          minikube delete
