name: CI for Minikube Deployment

on:
  push:
    branches:
      - main
    paths:
      - '*'  # Trigger on any file change

jobs:
  minikube:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Minikube
      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      # Step 3: Start Minikube
      - name: Start Minikube
        run: |
          minikube start --driver=docker
          kubectl cluster-info
          kubectl get nodes

      # ✅ Step 4: Build Docker image inside Minikube
      - name: Build Docker image inside Minikube
        run: |
          eval $(minikube docker-env)
          docker build -t local/example:latest .

      # ✅ Step 5: Apply Kubernetes Deployment
      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deploy/k8s.yaml
          kubectl wait --for=condition=ready pod -l app=example --timeout=3600s

      # Step 6: Check pod status
      - name: Check pod status
        run: |
          kubectl get pods -l app=example

      # Step 7: Check pod details
      - name: Check pod details
        run: |
          kubectl describe pod -l app=example

      # Step 8: Show pod logs (if failure)
      - name: Show pod logs if failed
        if: failure()
        run: |
          POD_NAME=$(kubectl get pods -l app=example -o jsonpath="{.items[0].metadata.name}")
          kubectl logs $POD_NAME || true

      # Step 9: Check Kubernetes events
      - name: Check Kubernetes events
        run: |
          kubectl get events --sort-by='.lastTimestamp'

      # Step 10: Get Service URL
      - name: Get Service URL
        id: get_service_url
        run: |
          SERVICE_URL=$(minikube service example --url)
          echo "Service URL: $SERVICE_URL"
          echo "::set-output name=url::$SERVICE_URL"

      # Step 11: Test the service with curl
      - name: Test the service with curl
        run: |
          curl ${{ steps.get_service_url.outputs.url }}

      # Step 12: Clean up Minikube
      - name: Clean up Minikube
        run: |
          minikube delete
