name: CI/CD with Kubernetes and Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Minikube
        uses: medyagh/setup-minikube@v0.0.14
        with:
          driver: docker
          kubernetes-version: 'v1.26.0'

      - name: Add Minikube to PATH
        run: |
          echo "$HOME/.minikube/bin" >> $GITHUB_PATH
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube addons enable ingress

      - name: Verify Minikube status
        run: |
          minikube status
          kubectl cluster-info
          kubectl get nodes

      - name: Set Docker environment
        run: |
          eval $(minikube -p minikube docker-env)
          echo "DOCKER_HOST=$(minikube ip):2376" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t example:latest .

      - name: Verify image
        run: |
          docker images
          minikube image ls

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deploy/k8s.yaml
          kubectl rollout status deployment/example --timeout=180s
          kubectl get pods,svc

      - name: Verify deployment
        run: |
          kubectl get pods -o wide
          kubectl describe deployment example
          kubectl logs -l app=example
