name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Minikube
        uses: medyagh/setup-minikube@v0.0.14

      - name: Enable Minikube Docker env
        run: |
          eval $(minikube -p minikube docker-env)

      - name: Build Docker image inside Minikube
        run: |
          docker build -t example:latest .

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deploy/k8s.yaml
          kubectl rollout status deployment/example --timeout=180s
